# Argus — discord.py observability SDK
# Copyright (C) 2026 AstorisTheBrave
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""``argus-fleet init``: scaffold a ready-to-run control plane.

Generates a ``.env`` (the secret + settings), a ``docker-compose.fleet.yml`` that
loads it via ``env_file``, and prints the exact member opt-in snippet with the
token/URL/group filled in. Pure, flag-driven functions so the artifacts are
testable; the interactive prompts are a thin wrapper around them. Secrets are
generated with :mod:`secrets` and shown once.
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass
from pathlib import Path

IMAGE = "ghcr.io/astoristhebrave/argus-fleet:latest"


@dataclass(slots=True)
class InitChoices:
    """The resolved answers an init run turns into artifacts."""

    token: str
    host: str = "0.0.0.0"
    port: int = 9190
    group: str = "default"
    namespace: str = "discord"
    prometheus_url: str | None = None
    cors_origins: str = ""
    public_url: str = "http://fleet-host:9190"


def generate_token() -> str:
    """A strong, URL-safe shared secret."""
    return secrets.token_urlsafe(32)


def build_env(choices: InitChoices) -> str:
    """The .env contents for the control plane."""
    lines = [
        "# Generated by `argus-fleet init`. Keep this file secret.",
        f"ARGUS_FLEET_HOST={choices.host}",
        f"ARGUS_FLEET_PORT={choices.port}",
        f"ARGUS_FLEET_TOKEN={choices.token}",
        f"ARGUS_NAMESPACE={choices.namespace}",
    ]
    if choices.prometheus_url:
        lines.append(f"ARGUS_FLEET_PROMETHEUS_URL={choices.prometheus_url}")
    if choices.cors_origins:
        lines.append(f"ARGUS_FLEET_CORS_ORIGINS={choices.cors_origins}")
    return "\n".join(lines) + "\n"


def build_compose(choices: InitChoices) -> str:
    """A docker-compose file that runs the image and loads .env via env_file."""
    return (
        "# Generated by `argus-fleet init`.\n"
        "services:\n"
        "  argus-fleet:\n"
        f"    image: {IMAGE}\n"
        "    restart: unless-stopped\n"
        "    env_file: .env\n"
        "    ports:\n"
        f'      - "{choices.port}:{choices.port}"\n'
        "    volumes:\n"
        "      - argus-fleet-state:/data\n"
        "volumes:\n"
        "  argus-fleet-state:\n"
    )


def member_snippet(choices: InitChoices) -> str:
    """The env vars an operator pastes onto each bot to opt into this fleet."""
    return (
        f"ARGUS_FLEET_URL={choices.public_url} \\\n"
        f"ARGUS_FLEET_TOKEN={choices.token} \\\n"
        f"ARGUS_FLEET_GROUP={choices.group} \\\n"
        "CLUSTER_ID=<unique-per-process> \\\n"
        "    python bot.py"
    )


def systemd_hint(env_path: Path) -> str:
    """The systemd line that loads the generated .env (dependency-free fallback)."""
    return f"EnvironmentFile={env_path.resolve()}"


def write_artifacts(choices: InitChoices, out_dir: Path) -> dict[str, Path]:
    """Write .env and docker-compose.fleet.yml into ``out_dir``; return their paths."""
    out_dir.mkdir(parents=True, exist_ok=True)
    env_path = out_dir / ".env"
    compose_path = out_dir / "docker-compose.fleet.yml"
    env_path.write_text(build_env(choices), encoding="utf-8")
    compose_path.write_text(build_compose(choices), encoding="utf-8")
    return {"env": env_path, "compose": compose_path}
